apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-chat-mongo-deployment
  namespace: mern-chat-app-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-mongo
  template:
    metadata:
      labels:
        app: chat-mongo
    spec:
      containers:
      - name: chat-mongo
        image: hamza2dev/mern-chat-mongo-2:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data-pvc