apiVersion: v1
kind: Service
metadata:
  name: mern-chat-mongo-service
  namespace: mern-chat-app-deps
spec:
  selector:
    app: chat-mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP