apiVersion: v1
kind: Service
metadata:
  name: mern-chat-backend-service
  namespace: mern-chat-app-core
spec:
  selector:
    app: chat-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

