apiVersion: v1
kind: Service
metadata:
  name: mern-chat-frontend-service
  namespace: mern-chat-app-core
spec:
  selector:
    app: chat-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP